### PR TITLE
Add --allow-root option for wordpress cli

### PR DESCRIPTION
**Pull request by aidanharris**
This pull request adds the option to use the Wordpress cli as root. I know this is generally a bad idea which is why the default is False (to not allow root). I needed this for use in a development environment (I had to use root because my Wordpress installation resides in a VirtualBox shared folder which can't be mounted as the www-data user because this user does not exist until Nginx is installed and configured).

### CODE REVIEW

**Review by fintanmm — APPROVED** [review]
Looks good @aidanharris, will fix conflicts.

**Comment by aboe76** [comment]
@fintanmm are you happy with the changes?

**Comment by fintanmm** [comment]
Hi @aboe76, yeah I think so.

**Comment by aboe76** [comment]
@aidanharris thanks for your work, @fintanmm thanks for reviewing.

**Pull request merged**
